source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.1"

gem "bootsnap", ">= 1.4.4", require: false
gem "puma", "~> 5.0"
gem "rack-cors"
gem "rails", "~> 6.1.4"
gem "sass-rails", ">= 6"
gem "sqlite3", "~> 1.4"
gem "tailcov", path: "../"
gem "view_component_storybook"
gem "webpacker", "~> 5.4.0"

group :development do
  gem "listen", "~> 3.3"
  gem "spring"
  gem "web-console", ">= 4.1.0"
end

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
